version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hiba
    container_name: hiba-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8001:80"
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: hiba
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: hiba
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./:/var/www
      - ./database/migrations:/app/database/migrations
    networks:
      - hiba

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hiba
      MYSQL_USER: hiba
      MYSQL_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql-migrations:/docker-entrypoint-initdb.d
    networks:
      - hiba

  nginx:
    image: nginx:alpine
    container_name: hiba-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hiba

  redis:
    image: redis:latest
    container_name: hiba-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hiba

networks:
  hiba:
    driver: bridge
