openapi: 3.0.3
info:
  title: Hiba
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: ''
      operationId: postApiRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: libero
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: wisoky.damaris@example.net
                phone:
                  type: string
                  description: ''
                  example: debitis
                password:
                  type: string
                  description: 'Must be at least 8 characters.'
                  example: _d!Vu@r+
              required:
                - name
                - email
                - phone
                - password
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: fbeahan@example.org
                password:
                  type: string
                  description: ''
                  example: quas
              required:
                - email
                - password
      security: []
  /api/store-public-key:
    post:
      summary: ''
      operationId: postApiStorePublicKey
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                publicKey:
                  type: string
                  description: ''
                  example: ut
              required:
                - publicKey
      security: []
  /api/export-companies:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/company/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the company.'
        example: mollitia
        required: true
        schema:
          type: string
  '/api/company/programs/{id}`':
    get:
      summary: ''
      operationId: getApiCompanyProgramsId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the .'
        example: consectetur
        required: true
        schema:
          type: string
  /api/export-categories:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/sambaza:
    post:
      summary: ''
      operationId: postApiSambaza
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/search-contact/{phoneNumber}':
    get:
      summary: ''
      operationId: getApiSearchContactPhoneNumber
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: phoneNumber
        description: ''
        example: velit
        required: true
        schema:
          type: string
  /api/redeem:
    post:
      summary: ''
      operationId: postApiRedeem
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                programId:
                  type: string
                  description: ''
                  example: voluptatem
                rewardId:
                  type: string
                  description: ''
                  example: sunt
                customerId:
                  type: string
                  description: ''
                  example: molestias
                amount:
                  type: number
                  description: ''
                  example: 12800.4659
              required:
                - programId
                - rewardId
                - customerId
                - amount
      security: []
  /api/program/rewards:
    get:
      summary: ''
      operationId: getApiProgramRewards
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                program:
                  type: string
                  description: ''
                  example: molestiae
              required:
                - program
      security: []
  /api/optIn:
    post:
      summary: ''
      operationId: postApiOptIn
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/customer-opted-in-programs:
    get:
      summary: ''
      operationId: getApiCustomerOptedInPrograms
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/update-profile:
    post:
      summary: ''
      operationId: postApiUpdateProfile
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/update-avatar:
    post:
      summary: ''
      operationId: postApiUpdateAvatar
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/change-password:
    post:
      summary: ''
      operationId: postApiChangePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/ads:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/unread-notifications:
    get:
      summary: ''
      operationId: getApiUnreadNotifications
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user-notifications:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
